### ISSUE TITLE
Compositions in Umple are generated as regular associations in Ecore instead of remaining compositions.

### ISSUE THREAD

**Issue by TimLethbridge** [umple-ucosp/umple#2120]
This issue was mentioned in a comment of #2101

```
class A {
  1 <@>- * B;
}

class B {
}
```

Generates the following Ecore

```
<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bs" upperBound="-1" eType="#//B" eOpposite="#//B/a" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" lowerBound="1" eType="#//A" eOpposite="#//A/bs" />
  </eClassifiers>
</ecore:EPackage>
```

Instead it should be generated as a composition (text to be added as a comment below)

**Comment by erica-d** [comment]
Expected generated composition:
```
<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bs" upperBound="-1" eType="#//B" containment="true" eOpposite="#//B/a" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" lowerBound="1" eType="#//A" eOpposite="#//A/bs" />
  </eClassifiers>
</ecore:EPackage>
```

**Comment by TimLethbridge** [comment]
So it looks as though the only thing required is to add
```
containment="true"
```

**Comment by erica-d** [comment]
I think so, yes

**Comment by TimLethbridge** [comment]
@erica-d I believe this is fixed now too. I will close this issue when you confirm it is OK from your perspective

**Comment by erica-d** [comment]
@TimLethbridge From what I can see on UmpleOnline, the containment="true" is still not showing up:
`<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bs" upperBound="-1" eType="#//B" eOpposite="#//B/a" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" lowerBound="1" eType="#//A" eOpposite="#//A/bs" />
  </eClassifiers>
</ecore:EPackage>`

**Comment by TimLethbridge** [comment]
Yes, I just merged the PR for containinment. It will pop up in about 15 minutes or so!


> On Apr 13, 2024, at 20:52, erica-d ***@***.***> wrote:
> 
> 
> @TimLethbridge From what I can see on UmpleOnline, the containment="true" is still not showing up:
> <?xml version="1.0" encoding="UTF-8"?> <ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="" nsPrefix="model"> <eClassifiers xsi:type="ecore:EClass" name="A"> <eStructuralFeatures xsi:type="ecore:EReference" name="bs" upperBound="-1" eType="#//B" eOpposite="#//B/a" /> </eClassifiers> <eClassifiers xsi:type="ecore:EClass" name="B"> <eStructuralFeatures xsi:type="ecore:EReference" name="a" lowerBound="1" eType="#//A" eOpposite="#//A/bs" /> </eClassifiers> </ecore:EPackage>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>


Timothy C. Lethbridge,
Mobile: 613-252-1850
http://www.site.uottawa.ca/~tcl

**Comment by TimLethbridge** [comment]
@erica-d  The continuous deployment stage has now completed and this PR appears in UmpleOnline ... and the containment now appears

**Comment by erica-d** [comment]
@TimLethbridge I see it now! Looks good, thanks for solving this issue too :)

**Comment by TimLethbridge** [comment]
Fixed by #2127
